chore(todo): setting up dev environment instead of cra
themetronome/frontend-study-themetronome pull request #67
Opened 2021-03-16 23:23 UTC by themetronome

affects: @site/app, @ui/test-todo-component

ISSUES CLOSED: #65

2021-03-17 08:59 UTC, TorinAsakura requested changes

2021-03-17 08:59 UTC, TorinAsakura commented on practice/todo/site/app/tsconfig.json
> +    "target": "es5",
мы не используем es5

2021-03-17 08:59 UTC, TorinAsakura commented on practice/todo/site/app/tsconfig.json
> +    "module": "commonjs",
мы не используем commonjs

2021-03-17 08:59 UTC, TorinAsakura commented on practice/todo/site/app/tsconfig.json
> +    "allowSyntheticDefaultImports": true
для чего?

2021-03-17 08:59 UTC, TorinAsakura commented on practice/todo/site/app/webpack.config.ts
> +export const mode = 'development'
а где production?

2021-03-17 09:55 UTC, themetronome commented on practice/todo/site/app/tsconfig.json
> +    "module": "commonjs",
> мы не используем commonjs

но вебпак же использует, как тогда использовать esm модули в вебпак конфиге?

2021-03-17 09:55 UTC, themetronome commented on practice/todo/site/app/tsconfig.json
> +    "allowSyntheticDefaultImports": true
https://webpack.js.org/configuration/configuration-languages/ - здесь пример конфига с опциями `esModuleInterop` и 'allowSyntheticDefaultImports', второй опции нет в конфиге от которого я наследуюсь, я и указал в локальном

2021-04-07 17:42 UTC, TFK70 requested changes

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/site/app/src/App.tsx
> +          <TodoListItem>learn react</TodoListItem>
И зачем нам тогда реакт нужен?
Ты должен принимать на вход данные на основе которых у тебя будут создаваться итемы, а не копипастить их

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/site/app/src/App.tsx
> +          <TodoListItem>learn react</TodoListItem>
И эта логика должна быть вынесена отсюда

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/site/app/src/App.tsx
> +            Все
Такой "константный" текст должен пробрасываться через intl

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/site/app/src/App.tsx
> +        <Layout display='flex' margin='16px 0'>
display: flex уже есть в дефолт пропсах лейаута
без него ничего бы и не работало

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/site/app/src/App.tsx
> +            placeholder='найдите задачу'
подобные куски тоже должны быть проброшены через intl

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/ui/button/src/types.ts
> +  border?: string
Не думаю что было весело копипастить пропсы из styled-system функций таким образом

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/ui/button/src/Button.ts
> +export const Button: StyledComponent<ButtonProps> = styled.button(
Суть в том что нет необходимости так делать. Когда ты используешь styled-system он сам типизирует пропсы соответственно тем функциям, которые ты использовал, так что border: string и прочее, что уже включает в себя styled-system нужно убрать из интерфейса

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/ui/button/src/Button.ts
> +export const Button: StyledComponent<ButtonProps> = styled.button(
И соответственно поставить под сомнение факт существования файлов с типами после этих изменений

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/ui/button/src/Button.ts
> +  system({ boxSizing: true }),
Мы так нигде не делаем. Используй тогда size целиком, если есть необходимость

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/ui/button/src/Button.ts
> +  transition: 'background-color .15s ease-in-out',
Это нужно сделать опциональным и выключенным по дефолту

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/ui/input/package.json
> +    "@types/styled-system": "^5.1.10"
Как раз благодаря этой зависимости styled-system и производит типизацию компонентов, к которым ты применяешь оттуда функции

Она нужна, но зачем она тебе была нужна если ты все-равно все описывал руками?

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/ui/layout/src/Layout.ts
> +export const Column = styled.div(layout, space, flexbox, boxSizing)
Вынеси в разные файлы, тут же каша происходит

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/components/header/package.json
> +  "name": "@components/header",
Твой хедер применим только для одной страницы, он не реиспользуемый и не конфигурируемый, так и назови его более конкретно

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/components/header/src/Header.tsx
> +export const Header: React.FC<HeaderProps> = ({ title, tasksStatus }) => {
Точнее он не должен быть конфигурируемым

В components находятся компоненты с уже готовой логикой, им не требуется брать что-то извне через пропсы, в противном случае можно создать шаблон для хедеров в ui, но это бред и так делать не надо, ты не так часто используешь этот компонент чтобы заморачиваться насчет шаблона

2021-04-07 17:42 UTC, TFK70 commented on practice/todo/components/todo-list-item/package.json
> +  "name": "@components/todo-list-item",
А это почему в components?

2021-04-08 10:50 UTC, themetronome commented on practice/todo/ui/layout/src/Layout.ts
> +export const Column = styled.div(layout, space, flexbox, boxSizing)
> Вынеси в разные файлы, тут же каша происходит

А в чём каша? Для разметки я импортирую нужный компонент, они же одного типа, почему не держать их в одном файле? Я подсматривал [сюда](https://github.com/Atlantis-Lab/serenity/blob/dev/frontend/ui/layout/src/Layout.ts)

2021-04-08 10:53 UTC, themetronome commented on practice/todo/components/header/package.json
> +  "name": "@components/header",
> Твой хедер применим только для одной страницы, он не реиспользуемый и не конфигурируемый, так и назови его более конкретно

А в рамках этой тудушки в принципе существует только одна страница, на счёт того, что не конфигурируемый - согласен

2021-04-08 10:56 UTC, themetronome commented on practice/todo/components/header/src/Header.tsx
> +export const Header: React.FC<HeaderProps> = ({ title, tasksStatus }) => {
> Точнее он не должен быть конфигурируемым
> 
> В components находятся компоненты с уже готовой логикой, им не требуется брать что-то извне через пропсы, в противном случае можно создать шаблон для хедеров в ui, но это бред и так делать не надо, ты не так часто используешь этот компонент чтобы заморачиваться насчет шаблона

Тогда не совсем понял в какую сторону двигаться. Я инкапсулирую в хедер ui-компоненты, которые уже принимают какие-то пропы?

2021-04-08 10:57 UTC, TFK70 commented on practice/todo/ui/layout/src/Layout.ts
> +export const Column = styled.div(layout, space, flexbox, boxSizing)
> > Вынеси в разные файлы, тут же каша происходит
> 
> А в чём каша? Для разметки я импортирую нужный компонент, они же одного типа, почему не держать их в одном файле? Я подсматривал [сюда](https://github.com/Atlantis-Lab/serenity/blob/dev/frontend/ui/layout/src/Layout.ts)

В теории ты можешь и так оставить, это действительно не критично

Но папка layout уже подразумевает в себе компоненты +- одного типа и ничего не мешало разнести Column, Row и Layout по разным файлам вместо того чтобы смешивать все это в одном

2021-04-08 11:00 UTC, TFK70 commented on practice/todo/components/header/src/Header.tsx
> +export const Header: React.FC<HeaderProps> = ({ title, tasksStatus }) => {
> > Точнее он не должен быть конфигурируемым
> > В components находятся компоненты с уже готовой логикой, им не требуется брать что-то извне через пропсы, в противном случае можно создать шаблон для хедеров в ui, но это бред и так делать не надо, ты не так часто используешь этот компонент чтобы заморачиваться насчет шаблона
> 
> Тогда не совсем понял в какую сторону двигаться. Я инкапсулирую в хедер ui-компоненты, которые уже принимают какие-то пропы?

Ты инкапсулируешь в компонентах из components законченную логику
Ты должен написать
```javascript
<Header />
```
И у тебя появился хедер

Ты пишешь
```javascript
<BookList />
```
И у тебя появляется список книг, они законченные и их ни к чему конфигурировать

2021-04-08 11:01 UTC, TFK70 commented on practice/todo/components/header/package.json
> +  "name": "@components/header",
> > Твой хедер применим только для одной страницы, он не реиспользуемый и не конфигурируемый, так и назови его более конкретно
> 
> А в рамках этой тудушки в принципе существует только одна страница, на счёт того, что не конфигурируемый - согласен

С неймингом да, можно и просто хедер оставить, это мои загоны были

2021-04-22 08:55 UTC, closed without merging